'use client'
import Link from 'next/link'
import { ArrowUpRight, Bookmark, Clock3, ShieldCheck, Camera, PlaySquare, Users } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { useDemo } from '@/store/ginger'
import { money, type Campaign } from '@/lib/ginger-data'
import { ProgressBar } from './shared'
export function CampaignCard({ campaign: c, compact = false }: { campaign: Campaign; compact?: boolean }) {
  const saved = useDemo(s => s.saved.includes(c.id)); const toggle = useDemo(s => s.toggleSaved)
  return <article className="panel campaign-card"><div className="relative overflow-hidden"><Link href={`/campaigns/${c.id}`} aria-label={`View ${c.title}`}><img className="campaign-image" src={c.image} alt={`${c.brand} campaign product photography`} loading="lazy" /></Link><div className="absolute left-3 top-3"><Badge variant="outline" className="bg-white/90">{c.category}</Badge></div><Button variant="outline" size="icon-sm" className="absolute right-3 top-3" aria-label={saved ? `Unsave ${c.title}` : `Save ${c.title}`} aria-pressed={saved} onClick={() => toggle(c.id)}><Bookmark fill={saved ? 'currentColor' : 'none'} /></Button></div><div className="p-5"><div className="mb-2 flex items-center gap-1.5 text-[10px] muted"><span className="font-medium text-foreground">{c.brand}</span><ShieldCheck className="size-3 text-success" /><span className="ml-auto flex items-center gap-1"><Clock3 className="size-3" />{c.days} days left</span></div><Link href={`/campaigns/${c.id}`}><h3 className="text-[15px] font-semibold leading-6 tracking-tight">{c.title}</h3></Link><div className="mt-4 flex items-center justify-between rounded-lg bg-background p-3"><div><p className="text-[9px] muted">Total prize pool</p><strong className="mt-1 block text-[17px] font-semibold tracking-tight">{money(c.budget)}</strong></div><div className="text-right"><p className="text-[9px] muted">Earn up to</p><strong className="mt-1 block text-sm font-semibold text-success">{money(c.tiers.at(-1)!.payout)} <span className="text-[9px] font-normal muted">/ clip</span></strong></div></div>{!compact && <div className="mt-4"><div className="mb-2 flex justify-between text-[10px] muted"><span>Pool remaining</span><span>{Math.round(c.remaining/c.budget*100)}%</span></div><ProgressBar value={c.remaining/c.budget*100} label="Budget remaining" /></div>}<div className="mt-4 flex items-center justify-between border-t pt-4"><div className="flex items-center gap-2 text-muted-foreground">{c.platforms.includes('Instagram') && <Instagram aria-label="Instagram" className="size-3.5" />}{c.platforms.includes('YouTube') && <Youtube aria-label="YouTube" className="size-4" />}<span className="ml-1 text-[9px]">{c.creators} creators</span></div><Link href={`/campaigns/${c.id}`} className="link-blue text-[10px]">View campaign <ArrowUpRight className="size-3.5" /></Link></div></div></article>
}
