'use client'
import Link from 'next/link'
import { useId, type ReactNode } from 'react'
import { ArrowRight, ShieldCheck, Search, LoaderCircle, Play, Sparkles, Compass } from 'lucide-react'
import { Button, buttonVariants } from '@/components/ui/button'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog'
import { Field, FieldLabel, FieldError } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group'
import { cn } from '@/lib/utils'
export function LinkButton({ href, children, variant = 'default', className }: { href: string; children: ReactNode; variant?: 'default'|'outline'|'secondary'|'ghost'; className?: string }) { return <Link href={href} className={cn(buttonVariants({ variant }), 'h-11 gap-2 px-5', className)}>{children}</Link> }
export function PageHeading({ eyebrow, title, description, children }: { eyebrow?: string; title: string; description?: string; children?: ReactNode }) { return <div className="page-heading"><div>{eyebrow && <div className="eyebrow mb-2">{eyebrow}</div>}<h1>{title}</h1>{description && <p className="muted mt-2 text-sm leading-relaxed">{description}</p>}</div>{children}</div> }
export function DemoNotice({ children }: { children?: ReactNode }) { return <Alert className="mb-6"><ShieldCheck /><AlertDescription>{children ?? 'Interactive demo · Fictional data. No real payments, verification, or account connections.'}</AlertDescription></Alert> }
export function Modal({ open, onClose, title, description, children }: { open: boolean; onClose: () => void; title: string; description?: string; children: ReactNode }) { return <Dialog open={open} onOpenChange={v => !v && onClose()}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description ?? 'Make changes to your GINGER demo.'}</DialogDescription></DialogHeader>{children}</DialogContent></Dialog> }
export function TextField({ label, value, onChange, error, type = 'text', placeholder, ...props }: { label: string; value: string; onChange: (v: string) => void; error?: string; type?: string; placeholder?: string; required?: boolean; min?: number; max?: number; step?: string; maxLength?: number }) { const id = useId(); return <Field data-invalid={!!error}><FieldLabel htmlFor={id}>{label}</FieldLabel><Input id={id} type={type} value={value} onChange={e => onChange(e.target.value)} aria-invalid={!!error} aria-describedby={error ? `${id}-error` : undefined} placeholder={placeholder} {...props} />{error && <FieldError id={`${id}-error`}>{error}</FieldError>}</Field> }
export function Filters({ items, value, onChange }: { items: string[]; value: string; onChange: (v: string) => void }) { return <ToggleGroup value={[value]} onValueChange={v => v.length && onChange(String(v[0]))} aria-label="Filter options" spacing={1}>{items.map(item => <ToggleGroupItem key={item} value={item}>{item}</ToggleGroupItem>)}</ToggleGroup> }
export function EmptyState({ title = 'No Campaigns Yet', description = "You haven't joined any campaigns. Explore the marketplace to find your first brand deal!", href, action }: { title?: string; description?: string; href?: string; action?: () => void }) { return <div className="flex flex-col items-center justify-center py-16 px-6 text-center w-full"><div className="relative mb-6 flex size-20 items-center justify-center rounded-full bg-sky-50"><div className="flex size-11 items-center justify-center rounded-xl border-[2.5px] border-dashed border-sky-300 bg-white"><Play className="size-4 text-sky-600 fill-sky-600 ml-0.5" /></div><Sparkles className="absolute -top-2 right-0 size-5 text-sky-400" /><Sparkles className="absolute bottom-2 -left-2 size-4 text-sky-300" /></div><h3 className="text-xl font-bold text-slate-900">{title}</h3><p className="mt-2.5 text-sm text-slate-500 max-w-xs mx-auto leading-relaxed">{description}</p><div className="mt-7">{href && <Link href={href} className="inline-flex h-10 items-center justify-center rounded-lg bg-sky-600 px-5 text-sm font-semibold text-white hover:bg-sky-700 transition-colors"><Compass className="mr-2 size-4" /> Explore Campaigns</Link>}{action && <Button variant="outline" onClick={action} className="mt-3">Reset filters</Button>}</div></div> }
export function ProgressBar({ value, label }: { value: number; label: string }) { return <div role="progressbar" aria-label={label} aria-valuenow={Math.round(value)} aria-valuemin={0} aria-valuemax={100} className="progress-track"><div className="progress-fill" style={{ width: `${Math.max(0,Math.min(100,value))}%` }} /></div> }
export function PendingButton({ pending, children }: { pending: boolean; children: ReactNode }) { return <Button type="submit" disabled={pending}>{pending && <LoaderCircle data-icon="inline-start" className="animate-spin" />}{children}</Button> }
export function Avatar({ name, color = 'blue', large = false }: { name: string; color?: string; large?: boolean }) { return <span className={cn('avatar-initial', `tone-${color}`, large && '!size-16 !text-xl')}>{name.split(' ').map(n => n[0]).slice(0,2).join('')}</span> }
