export type Tier = { views: number; payout: number }
export type Campaign = { id: string; title: string; brand: string; category: string; image: string; color: string; platforms: string[]; budget: number; remaining: number; days: number; creators: number; location: string; tiers: Tier[]; description: string; owned?: boolean }
export type Submission = { id: string; campaignId: string; url: string; videoId: string; platform: string; views: number; paid: number; flagged: boolean }
export type Transaction = { id: string; title: string; amount: number; type: 'Earnings' | 'Withdrawals' | 'Deposits' | 'Escrow'; status: 'Completed' | 'Pending' | 'In escrow'; date: string }
export type Conversation = { id: string; name: string; context: string; unread: boolean; messages: { id: string; text: string; mine: boolean }[] }
export type Profile = { name: string; handle: string; role: string; bio: string; location: string; niche: string; notifications: boolean; discoverable: boolean; destination: string }
export const money = (paise: number, decimals = false) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: decimals ? 2 : 0, minimumFractionDigits: decimals ? 2 : 0 }).format(paise / 100)
export const count = (value: number) => Intl.NumberFormat('en', { notation: value >= 10000 ? 'compact' : 'standard', maximumFractionDigits: 1 }).format(value)
export const tiers: Tier[] = [{ views: 1000, payout: 50000 }, { views: 10000, payout: 300000 }, { views: 50000, payout: 1500000 }]
export const campaigns: Campaign[] = [
  { id: 'daily-glow', title: 'Your everyday glow, on camera.', brand: 'Dew & Co.', category: 'Beauty & skincare', image: '/images/skincare.png', color: 'pink', platforms: ['Instagram', 'YouTube'], budget: 25000000, remaining: 18000000, days: 12, creators: 128, location: 'Pan-India', tiers, description: 'Turn your everyday skincare ritual into a story. Create an authentic 15–45 second video showing how Dew & Co. fits into your morning routine.' },
  { id: 'fresh-perspective', title: 'A little fizz. A fresh perspective.', brand: 'Lime Social', category: 'Food & drinks', image: '/images/drink.png', color: 'green', platforms: ['Instagram', 'YouTube', 'TikTok'], budget: 15000000, remaining: 12750000, days: 18, creators: 86, location: 'Pan-India', tiers: [{ views: 1000, payout: 50000 }, { views: 10000, payout: 250000 }, { views: 50000, payout: 1000000 }], description: 'Bring a little refreshment to your feed. Capture your first sip, your afternoon reset, or a day out with friends and Lime Social.' },
  { id: 'sound-on', title: 'Your world. A better soundtrack.', brand: 'Sonic', category: 'Tech & gadgets', image: '/images/headphones.png', color: 'blue', platforms: ['YouTube', 'Instagram'], budget: 50000000, remaining: 32000000, days: 7, creators: 214, location: 'Pan-India', tiers: [{ views: 1000, payout: 100000 }, { views: 10000, payout: 500000 }, { views: 100000, payout: 2500000 }], description: 'Show your audience what immersive audio feels like. Make an unboxing, a desk-setup clip, or a day-in-the-life with Sonic headphones.', owned: true },
  { id: 'weekend-reset', title: 'Make room for a weekend reset.', brand: 'Dew & Co.', category: 'Lifestyle', image: '/images/skincare.png', color: 'pink', platforms: ['Instagram'], budget: 8000000, remaining: 4800000, days: 5, creators: 42, location: 'Mumbai', tiers, description: 'Film a mindful weekend routine at our Mumbai pop-up. Share your real experience and your favorite little moment.' },
  { id: 'sip-local', title: 'Meet your new neighborhood favorite.', brand: 'Lime Social', category: 'Food & drinks', image: '/images/drink.png', color: 'green', platforms: ['Instagram'], budget: 6000000, remaining: 5400000, days: 21, creators: 31, location: 'Bengaluru', tiers: [{ views: 1000, payout: 50000 }, { views: 10000, payout: 200000 }], description: 'Discover our new Bengaluru tasting room and make an honest, fun short-form visit guide.' },
  { id: 'desk-upgrade', title: 'The upgrade your desk deserves.', brand: 'Sonic', category: 'Tech & gadgets', image: '/images/headphones.png', color: 'blue', platforms: ['YouTube'], budget: 20000000, remaining: 16000000, days: 14, creators: 63, location: 'Pan-India', tiers, description: 'Give your setup a refresh and show the everyday details that help you do your best work.' },
]
export const creators = [
  { id: 'aanya', name: 'Aanya Sharma', handle: '@aanya.creates', niche: 'Beauty & skincare', followers: 165000, engagement: '8.4%', location: 'Mumbai', initials: 'AS', color: 'pink', rate: 1500000 },
  { id: 'rohit', name: 'Rohit Mehta', handle: '@rohit.tech', niche: 'Tech & gadgets', followers: 245000, engagement: '6.8%', location: 'Bengaluru', initials: 'RM', color: 'blue', rate: 2500000 },
  { id: 'priya', name: 'Priya Kapoor', handle: '@priya.living', niche: 'Lifestyle', followers: 98000, engagement: '9.2%', location: 'New Delhi', initials: 'PK', color: 'green', rate: 1200000 },
  { id: 'kabir', name: 'Kabir Shah', handle: '@kabir.eats', niche: 'Food & drinks', followers: 132000, engagement: '7.6%', location: 'Mumbai', initials: 'KS', color: 'pink', rate: 1800000 },
  { id: 'isha', name: 'Isha Patel', handle: '@isha.moves', niche: 'Fitness', followers: 81000, engagement: '8.1%', location: 'Pune', initials: 'IP', color: 'green', rate: 1000000 },
  { id: 'arjun', name: 'Arjun Verma', handle: '@arjun.explores', niche: 'Travel', followers: 192000, engagement: '6.9%', location: 'Goa', initials: 'AV', color: 'blue', rate: 2200000 },
]
export const initialProfile: Profile = { name: 'Alex Morgan', handle: '@alex.creates', role: 'Creator', bio: 'Making everyday moments worth watching. Lifestyle, tech, and a little creativity.', location: 'Mumbai, India', niche: 'Lifestyle', notifications: true, discoverable: true, destination: 'Demo Bank •••• 4892' }
export const initialTransactions: Transaction[] = [
  { id: 't1', title: 'Dew & Co. · Milestone payout', amount: 300000, type: 'Earnings', status: 'Completed', date: '2026-09-15' },
  { id: 't2', title: 'Withdrawal to demo bank •••• 4892', amount: -500000, type: 'Withdrawals', status: 'Completed', date: '2026-09-14' },
  { id: 't3', title: 'Sonic · Creator reward', amount: 1500000, type: 'Earnings', status: 'Completed', date: '2026-09-12' },
  { id: 't4', title: 'Demo wallet top-up', amount: 1000000, type: 'Deposits', status: 'Completed', date: '2026-09-10' },
]
export const initialConversations: Conversation[] = [{ id: 'sonic', name: 'Sonic Studio', context: 'Your world. A better soundtrack.', unread: true, messages: [{ id: 'm1', text: 'Hi Alex! We love your creative style. Would you be interested in creating a desk-setup video for Sonic?', mine: false }, { id: 'm2', text: 'Absolutely! I have a few ideas for an everyday listening routine.', mine: true }, { id: 'm3', text: 'Sounds great. The campaign brief has everything you need. Looking forward to seeing your take!', mine: false }] }, { id: 'dew', name: 'Dew & Co.', context: 'Your everyday glow, on camera.', unread: true, messages: [{ id: 'm4', text: 'Welcome to the campaign! Let us know if you have any questions about the brief.', mine: false }] }]
